[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://jcdqwmzydjjfhoyqjcee.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZHF3bXp5ZGpqZmhveXFqY2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjU5NDUsImV4cCI6MjA1ODIwMTk0NX0.pJ3JYkWcig7aNYRJCgJ02WyJ6UbZwrkAVOBd0N2-k-w"
  SUPABASE_URL = "https://jcdqwmzydjjfhoyqjcee.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZHF3bXp5ZGpqZmhveXFqY2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjU5NDUsImV4cCI6MjA1ODIwMTk0NX0.pJ3JYkWcig7aNYRJCgJ02WyJ6UbZwrkAVOBd0N2-k-w"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZHF3bXp5ZGpqZmhveXFqY2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjU5NDUsImV4cCI6MjA1ODIwMTk0NX0.pJ3JYkWcig7aNYRJCgJ02WyJ6UbZwrkAVOBd0N2-k-w"
