[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Don't redirect everything to index.html - let Next.js handle routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Include necessary external modules for serverless functions
[functions]
  external_node_modules = ["@supabase/supabase-js"]

# This ensures Next.js ISR and SSR work properly
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false 